version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: ./src/dockerfile
    network_mode: host
    volumes:
      - ./:/app
    command: python -m src.server.app
  client:
    build:
      context: ./
      dockerfile: ./src/dockerfile
    network_mode: host
    depends_on:
      - server
    volumes:
      - ./:/app
    command: python -m src.client.app
