# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/proto/interface.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="src/proto/interface.proto",
    package="interface",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x19src/proto/interface.proto\x12\tinterface"\x1d\n\nWeightPush\x12\x0f\n\x07message\x18\x01 \x01(\t"\x1d\n\nWeightPull\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3'
    ),
)


_WEIGHTPUSH = _descriptor.Descriptor(
    name="WeightPush",
    full_name="interface.WeightPush",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="interface.WeightPush.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=40,
    serialized_end=69,
)


_WEIGHTPULL = _descriptor.Descriptor(
    name="WeightPull",
    full_name="interface.WeightPull",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="message",
            full_name="interface.WeightPull.message",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=71,
    serialized_end=100,
)

DESCRIPTOR.message_types_by_name["WeightPush"] = _WEIGHTPUSH
DESCRIPTOR.message_types_by_name["WeightPull"] = _WEIGHTPULL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeightPush = _reflection.GeneratedProtocolMessageType(
    "WeightPush",
    (_message.Message,),
    {
        "DESCRIPTOR": _WEIGHTPUSH,
        "__module__": "src.proto.interface_pb2"
        # @@protoc_insertion_point(class_scope:interface.WeightPush)
    },
)
_sym_db.RegisterMessage(WeightPush)

WeightPull = _reflection.GeneratedProtocolMessageType(
    "WeightPull",
    (_message.Message,),
    {
        "DESCRIPTOR": _WEIGHTPULL,
        "__module__": "src.proto.interface_pb2"
        # @@protoc_insertion_point(class_scope:interface.WeightPull)
    },
)
_sym_db.RegisterMessage(WeightPull)


# @@protoc_insertion_point(module_scope)
